name: Repository Events
on: [push,pull_request,issues]

jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps: 
        - run: |
            echo $GITHUB_SHA
            echo $GUTHUB_REF
        - uses: actions/checkout@v3
